name: Check Homework

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  check_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Create homework_checker.py from secret
        run: |
          echo "${{ secrets.HOMEWORK_CHECKER }}" > homework_checker.py

      - name: Run homework checker
        id: run-homework-checker
        run: |
          echo "Running homework checker..."
          python homework_checker.py > result.log

          # Проверка завершения работы скрипта
          if [ $? -ne 0 ]; then
            echo "Homework checker failed!" >> result.log
            exit 1
          fi

          # Проверяем, что файл result.log не пустой
          if [ ! -s result.log ]; then
            echo "Error: result.log is empty after running homework checker" >> result.log
            exit 1
          fi

      - name: Check if result.log is empty
        run: |
          # Проверяем, существует ли файл result.log
          if [ ! -f result.log ]; then
            echo "Error: result.log does not exist" >> result.log
            exit 1
          fi

          # Проверяем, что файл result.log не пустой
          if [ ! -s result.log ]; then
            echo "Error: result.log is empty" >> result.log
            exit 1
          fi

          echo "result.log is not empty, proceeding..."

      - name: Debug result.log content
        run: |
          echo "Contents of result.log:"
          cat result.log || echo "Failed to read result.log"

      - name: Add feedback as a comment on 
